version: '3'

services:
  service:
    image: "dqw4w9wgxcq/osrs-pathfinder-service"
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - TILE_SERVICE_ADDRESS=http://tile-service:8080
    volumes:
      - .:/workdir

  tile-service:
    restart: unless-stopped
    image: "dqw4w9wgxcq/osrs-pathfinder-tile-service"
    volumes:
      - .:/workdir
